<?php

namespace AppBundle\Repository;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordRepository extends \Doctrine\ORM\EntityRepository
{
    public function getExcludedKeywords($where = array())
    {
        $query = $this->createQueryBuilder('k')
            ->where('k.keywordId != :keywordId')
            ->andWhere('k.name = :name')
            ->andWhere('k.user = :user')
            ->setParameter('name', $where['name'])
            ->setParameter('user', $where['user'])
            ->setParameter('keywordId', $where['keywordId']);
        return $query->getQuery()->getResult();
    }
}
