services:
        session.service:
            class: AppBundle\Service\SessionService
            arguments: ['@session']

        http.service:
            class: AppBundle\Service\HttpService
            arguments: ['@http_client']

        keyword.service:
            class: AppBundle\Service\KeywordService
            arguments: ['@doctrine.orm.entity_manager']

        user.service:
            class: AppBundle\Service\UserService
            arguments: ['@doctrine.orm.entity_manager']

        redis.service:
            class: AppBundle\Service\RedisService
            arguments: []

        security.user_provider:
            class: AppBundle\Security\UserProvider
            arguments: ['@doctrine.orm.entity_manager']

        http_client:
            class: GuzzleHttp\Client
            arguments:
                - base_uri: %api_host%
                  timeout: 30
                  connect_timeout: 5