services:
        session.service:
            class: AppBundle\Service\SessionService
            arguments: ['@session']

        security.user_provider:
            class: AppBundle\Security\UserProvider
            arguments: ['@doctrine.orm.entity_manager']